# Generated by Django 4.1 on 2022-09-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_instructor_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='semastes',
            field=models.ManyToManyField(to='main.semaster'),
        ),
    ]
