# Generated by Django 4.1 on 2022-08-19 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_major_faculty_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MajorInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.instructor')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.major')),
            ],
        ),
        migrations.AddField(
            model_name='instructor',
            name='major',
            field=models.ManyToManyField(through='main.MajorInstructor', to='main.major'),
        ),
    ]
