# Generated by Django 4.1 on 2022-08-19 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_instructor_majorinstructor_instructor_major'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('credit', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MajorCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.course')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.major')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.instructor')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='major',
            field=models.ManyToManyField(through='main.MajorCourse', to='main.major'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='course',
            field=models.ManyToManyField(through='main.InstructorCourse', to='main.course'),
        ),
    ]
