# Generated by Django 4.1 on 2022-08-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_course_majorcourse_instructorcourse_course_major_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prerequisite',
            field=models.ManyToManyField(blank=True, to='main.course'),
        ),
    ]
