# Generated by Django 4.1 on 2022-08-21 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_course_options_alter_courseselection_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='course',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='major',
        ),
        migrations.AddField(
            model_name='instructor',
            name='courses',
            field=models.ManyToManyField(through='main.InstructorCourse', to='main.course', verbose_name='درس'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='majors',
            field=models.ManyToManyField(through='main.MajorInstructor', to='main.major', verbose_name='رشته'),
        ),
        migrations.AlterField(
            model_name='course',
            name='credit',
            field=models.SmallIntegerField(verbose_name='تعداد واحد'),
        ),
        migrations.AlterField(
            model_name='course',
            name='major',
            field=models.ManyToManyField(through='main.MajorCourse', to='main.major', verbose_name='رشته'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=30, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisite',
            field=models.ManyToManyField(blank=True, to='main.course', verbose_name='دروس پیشنیاز'),
        ),
        migrations.AlterField(
            model_name='courseselection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.section', verbose_name='سکشن'),
        ),
        migrations.AlterField(
            model_name='courseselection',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student', verbose_name='دانشجو'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='established_year',
            field=models.DateField(verbose_name='سال تاسیس'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='manager',
            field=models.CharField(max_length=30, verbose_name='مدیر'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=30, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='نام\u200cخانوادگی'),
        ),
        migrations.AlterField(
            model_name='instructorcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.course', verbose_name='درس'),
        ),
        migrations.AlterField(
            model_name='instructorcourse',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.instructor', verbose_name='مدرس'),
        ),
        migrations.AlterField(
            model_name='major',
            name='area_of_interest',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='گرایش'),
        ),
        migrations.AlterField(
            model_name='major',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.faculty', verbose_name='دانشکده'),
        ),
        migrations.AlterField(
            model_name='major',
            name='grade',
            field=models.CharField(choices=[('B', 'کارشناسی'), ('M', 'کارشناسی ارشد'), ('D', 'دکترا')], default='B', max_length=1, verbose_name='مقطع'),
        ),
        migrations.AlterField(
            model_name='major',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='majorcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.course', verbose_name='درس'),
        ),
        migrations.AlterField(
            model_name='majorcourse',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.major', verbose_name='رشته'),
        ),
        migrations.AlterField(
            model_name='majorinstructor',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.instructor', verbose_name='مدرس'),
        ),
        migrations.AlterField(
            model_name='majorinstructor',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.major', verbose_name='رشته'),
        ),
        migrations.AlterField(
            model_name='section',
            name='class_time',
            field=models.CharField(max_length=100, verbose_name='زمان'),
        ),
        migrations.AlterField(
            model_name='section',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course', verbose_name='درس'),
        ),
        migrations.AlterField(
            model_name='section',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.instructor', verbose_name='مدرس'),
        ),
        migrations.AlterField(
            model_name='section',
            name='student',
            field=models.ManyToManyField(through='main.CourseSelection', to='main.student', verbose_name='دانشجویان'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='نام\u200cخانوادگی'),
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.major', verbose_name='رشته'),
        ),
    ]
