# Generated by Django 4.1 on 2022-08-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_faculty_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='national_id',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
