# Generated by Django 4.1 on 2022-08-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_student_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='national_id',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
