# Generated by Django 4.1 on 2022-08-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_course_code_alter_instructor_national_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credit',
            field=models.PositiveSmallIntegerField(verbose_name='تعداد واحد'),
        ),
    ]
