# Generated by Django 4.1 on 2022-08-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_course_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='code',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
