# Generated by Django 4.1 on 2022-08-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_major_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='کد درس'),
        ),
    ]
