# Generated by Django 4.1 on 2022-08-22 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_major_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='majorcourse',
            unique_together={('major', 'course')},
        ),
    ]
